# **Tugas Individu - Machine Learning - No.1**

Link ke Google Collab

In [14]:
print("https://colab.research.google.com/drive/1wBJQUgc1xQ2F9PREd6wBpuXfdSXmU81S?usp=sharing")

https://colab.research.google.com/drive/1wBJQUgc1xQ2F9PREd6wBpuXfdSXmU81S?usp=sharing


#Import Dataset

Import Library

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn

Load Dataset haberman.data

In [19]:
# Mengupload menggunakan metode import file dari directory PC
from google.colab import files
load_dataset = files.upload()

Saving haberman.data to haberman (1).data


In [20]:
import io
df = pd.read_csv(io.BytesIO(load_dataset['haberman.data']))

Membaca file yang telah diupload

In [21]:
data = pd.read_csv("haberman.data")
data.head

<bound method NDFrame.head of      30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]>

#Data Preprocessing dan Feature Scaling

Menload Dataset menjadi x dan y

In [22]:
# Memilih cell tertentu dari dataset
X = data.iloc[:, [0, 1, 2]].values
y = data.iloc[:, -1].values

Split Dataset menjadi Test dan Train

In [23]:
# Import sklearn untuk mensplit
# Split  menjadi test dan train dengan test_size = 0.2
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

Scaling Dataset

In [24]:
# Feature Scalling untuk mentrain dan mentest set dari variabel indepen untuk di kurangi menjadi value yang lebih kecil
from sklearn.preprocessing import StandardScaler

# Membuat method untuk di scaling
scaler = StandardScaler()

# Menscaling dataset x_train dan x_test
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Algoritma KNN sebagai Model Classifier

In [26]:
# Membuat dan mentrain KNN model dengan training dataset
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

Membandingkan True dan Predict Value

In [27]:
y_test

array([1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1,
       1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1])

In [28]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1])

#Evaluasi Model

In [29]:
# Import sklearn matrix untuk evaluasi dan akurasi model dari algoritma KNN
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

Accuracy_score

In [33]:
# Hasil prediksi menggunakan accuracy_score
ac = accuracy_score(y_test,y_pred)
print('Testing Accuracy = {}'.format(ac))

Testing Accuracy = 0.5737704918032787


Confusion_matrix

In [34]:
# Hasil prediksi menggunakan confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix = ')
print(cm)

Confusion matrix = 
[[34  6]
 [20  1]]


Classification_report

In [35]:
# Hasil prediksi menggunakan classification_report
cr = classification_report(y_test,y_pred)
print('classification report = ')
print(cr)

classification report = 
              precision    recall  f1-score   support

           1       0.63      0.85      0.72        40
           2       0.14      0.05      0.07        21

    accuracy                           0.57        61
   macro avg       0.39      0.45      0.40        61
weighted avg       0.46      0.57      0.50        61



# Uji Ulang Menggunakan Naive Bayes

Train Dataset dengan NaiveBayes

In [38]:
# Import sklearn untuk Naive Bayes
from sklearn.naive_bayes import GaussianNB

# Membuat method classifie
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

Evaluasi : confusion_matrix

In [39]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

y_pred = classifier.predict(X_test)

print('Confusion matrix = ')
print(cm)

Confusion matrix = 
[[34  6]
 [20  1]]


Evaluasi : accuracy_score

In [40]:
ac = accuracy_score(y_test,y_pred)
print('Testing Accuracy = {}'.format(ac))

Testing Accuracy = 0.5901639344262295


Evaluasi : classification_report

In [41]:
cr = classification_report(y_test,y_pred)
print('classification report = ')
print(cr)

classification report = 
              precision    recall  f1-score   support

           1       0.64      0.88      0.74        40
           2       0.17      0.05      0.07        21

    accuracy                           0.59        61
   macro avg       0.40      0.46      0.41        61
weighted avg       0.47      0.59      0.51        61



# Uji Ulang menggunakan SVM

In [42]:
# Import Sklearn SVM
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

Memprediksi Hasil Test

In [43]:
y_pred = classifier.predict(X_test)

Evaluasi : confusion_matrix

In [44]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[36,  4],
       [20,  1]])

Evaluasi : accuracy_score

In [45]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print('Testing Accuracy = {}'.format(ac))

Testing Accuracy = 0.6065573770491803


Evaluasi : classification_report

In [46]:
from sklearn.metrics import classification_report
cr = classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           1       0.64      0.90      0.75        40
           2       0.20      0.05      0.08        21

    accuracy                           0.61        61
   macro avg       0.42      0.47      0.41        61
weighted avg       0.49      0.61      0.52        61



# Kesimpulan

In [51]:
print("KNN - Testing Accuracy : 0.573")
print("Bayes - Testing Accuracy : 0.59")
print("SVM - Testing Accuracy : 0.606")

KNN - Testing Accuracy : 0.573
SVM - Testing Accuracy : 0.59
Bayes - Testing Accuracy : 0.606


Karena SVM memiliki Testing Accuracy tertinggi, maka SVM adalah classifier terbaik untuk dataset haberman.data